<?php
/**
 * DetailedInformationOfTheSubmittedDocument
 *
 * PHP version 5
 *
 * @category Class
 * @package  invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IdCheck.IO API
 *
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace model;

use \ArrayAccess;

/**
 * DetailedInformationOfTheSubmittedDocument Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedInformationOfTheSubmittedDocument implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Detailed information of the submitted document';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'emit_country' => 'string',
        'emit_date' => '\model\EventDate',
        'expiration_date' => '\model\EventDate',
        'document_number' => 'string',
        'extra_infos' => '\model\GenericData[]'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'emit_country' => 'emitCountry',
        'emit_date' => 'emitDate',
        'expiration_date' => 'expirationDate',
        'document_number' => 'documentNumber',
        'extra_infos' => 'extraInfos'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'emit_country' => 'setEmitCountry',
        'emit_date' => 'setEmitDate',
        'expiration_date' => 'setExpirationDate',
        'document_number' => 'setDocumentNumber',
        'extra_infos' => 'setExtraInfos'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'emit_country' => 'getEmitCountry',
        'emit_date' => 'getEmitDate',
        'expiration_date' => 'getExpirationDate',
        'document_number' => 'getDocumentNumber',
        'extra_infos' => 'getExtraInfos'
    );

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['emit_country'] = isset($data['emit_country']) ? $data['emit_country'] : null;
        $this->container['emit_date'] = isset($data['emit_date']) ? $data['emit_date'] : null;
        $this->container['expiration_date'] = isset($data['expiration_date']) ? $data['expiration_date'] : null;
        $this->container['document_number'] = isset($data['document_number']) ? $data['document_number'] : null;
        $this->container['extra_infos'] = isset($data['extra_infos']) ? $data['extra_infos'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        return true;
    }


    /**
     * Gets emit_country
     * @return string
     */
    public function getEmitCountry()
    {
        return $this->container['emit_country'];
    }

    /**
     * Sets emit_country
     * @param string $emit_country emit country
     * @return $this
     */
    public function setEmitCountry($emit_country)
    {
        $this->container['emit_country'] = $emit_country;

        return $this;
    }

    /**
     * Gets emit_date
     * @return \model\EventDate
     */
    public function getEmitDate()
    {
        return $this->container['emit_date'];
    }

    /**
     * Sets emit_date
     * @param \model\EventDate $emit_date
     * @return $this
     */
    public function setEmitDate($emit_date)
    {
        $this->container['emit_date'] = $emit_date;

        return $this;
    }

    /**
     * Gets expiration_date
     * @return \model\EventDate
     */
    public function getExpirationDate()
    {
        return $this->container['expiration_date'];
    }

    /**
     * Sets expiration_date
     * @param \model\EventDate $expiration_date
     * @return $this
     */
    public function setExpirationDate($expiration_date)
    {
        $this->container['expiration_date'] = $expiration_date;

        return $this;
    }

    /**
     * Gets document_number
     * @return string
     */
    public function getDocumentNumber()
    {
        return $this->container['document_number'];
    }

    /**
     * Sets document_number
     * @param string $document_number document number
     * @return $this
     */
    public function setDocumentNumber($document_number)
    {
        $this->container['document_number'] = $document_number;

        return $this;
    }

    /**
     * Gets extra_infos
     * @return \model\GenericData[]
     */
    public function getExtraInfos()
    {
        return $this->container['extra_infos'];
    }

    /**
     * Sets extra_infos
     * @param \model\GenericData[] $extra_infos additional informations
     * @return $this
     */
    public function setExtraInfos($extra_infos)
    {
        $this->container['extra_infos'] = $extra_infos;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\invoker\ObjectSerializer::sanitizeForSerialization($this));
    }
}


