<?php
/**
 * ResultResponse
 *
 * PHP version 5
 *
 * @category Class
 * @package  idcheckio
 * @author   Swaagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IdCheck.IO API
 *
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace idcheckio\model;

use \ArrayAccess;

/**
 * ResultResponse Class Doc Comment
 *
 * @category    Class
 * @package     idcheckio
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ResultResponse implements ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'ResultResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = [
        'uid' => 'string',
        'analysis_ref_uid' => 'string',
        'check_report_summary' => '\idcheckio\model\CheckSummaryOfTheSubmittedDocument',
        'document_classification' => '\idcheckio\model\ClassificationOfTheSubmittedDocument',
        'document_detail' => '\idcheckio\model\DetailedInformationOfTheSubmittedDocument',
        'holder_detail' => '\idcheckio\model\DetailedInformationOfTheHolderOfTheSubmittedDocument',
        'mrz' => '\idcheckio\model\Mrz',
        'controls' => '\idcheckio\model\ControlGroup[]',
        'image' => '\idcheckio\model\ExtractedImage[]'
    ];

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = [
        'uid' => 'uid',
        'analysis_ref_uid' => 'analysisRefUid',
        'check_report_summary' => 'checkReportSummary',
        'document_classification' => 'documentClassification',
        'document_detail' => 'documentDetail',
        'holder_detail' => 'holderDetail',
        'mrz' => 'mrz',
        'controls' => 'controls',
        'image' => 'image'
    ];


    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = [
        'uid' => 'setUid',
        'analysis_ref_uid' => 'setAnalysisRefUid',
        'check_report_summary' => 'setCheckReportSummary',
        'document_classification' => 'setDocumentClassification',
        'document_detail' => 'setDocumentDetail',
        'holder_detail' => 'setHolderDetail',
        'mrz' => 'setMrz',
        'controls' => 'setControls',
        'image' => 'setImage'
    ];


    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = [
        'uid' => 'getUid',
        'analysis_ref_uid' => 'getAnalysisRefUid',
        'check_report_summary' => 'getCheckReportSummary',
        'document_classification' => 'getDocumentClassification',
        'document_detail' => 'getDocumentDetail',
        'holder_detail' => 'getHolderDetail',
        'mrz' => 'getMrz',
        'controls' => 'getControls',
        'image' => 'getImage'
    ];

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    public static function setters()
    {
        return self::$setters;
    }

    public static function getters()
    {
        return self::$getters;
    }

    

    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     * @param mixed[] $data Associated array of property values initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['uid'] = isset($data['uid']) ? $data['uid'] : null;
        $this->container['analysis_ref_uid'] = isset($data['analysis_ref_uid']) ? $data['analysis_ref_uid'] : null;
        $this->container['check_report_summary'] = isset($data['check_report_summary']) ? $data['check_report_summary'] : null;
        $this->container['document_classification'] = isset($data['document_classification']) ? $data['document_classification'] : null;
        $this->container['document_detail'] = isset($data['document_detail']) ? $data['document_detail'] : null;
        $this->container['holder_detail'] = isset($data['holder_detail']) ? $data['holder_detail'] : null;
        $this->container['mrz'] = isset($data['mrz']) ? $data['mrz'] : null;
        $this->container['controls'] = isset($data['controls']) ? $data['controls'] : null;
        $this->container['image'] = isset($data['image']) ? $data['image'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = [];

        if ($this->container['uid'] === null) {
            $invalid_properties[] = "'uid' can't be null";
        }
        if ($this->container['analysis_ref_uid'] === null) {
            $invalid_properties[] = "'analysis_ref_uid' can't be null";
        }
        if ($this->container['check_report_summary'] === null) {
            $invalid_properties[] = "'check_report_summary' can't be null";
        }
        if ($this->container['document_classification'] === null) {
            $invalid_properties[] = "'document_classification' can't be null";
        }
        if ($this->container['document_detail'] === null) {
            $invalid_properties[] = "'document_detail' can't be null";
        }
        if ($this->container['holder_detail'] === null) {
            $invalid_properties[] = "'holder_detail' can't be null";
        }
        if ($this->container['mrz'] === null) {
            $invalid_properties[] = "'mrz' can't be null";
        }
        if ($this->container['controls'] === null) {
            $invalid_properties[] = "'controls' can't be null";
        }
        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {

        if ($this->container['uid'] === null) {
            return false;
        }
        if ($this->container['analysis_ref_uid'] === null) {
            return false;
        }
        if ($this->container['check_report_summary'] === null) {
            return false;
        }
        if ($this->container['document_classification'] === null) {
            return false;
        }
        if ($this->container['document_detail'] === null) {
            return false;
        }
        if ($this->container['holder_detail'] === null) {
            return false;
        }
        if ($this->container['mrz'] === null) {
            return false;
        }
        if ($this->container['controls'] === null) {
            return false;
        }
        return true;
    }


    /**
     * Gets uid
     * @return string
     */
    public function getUid()
    {
        return $this->container['uid'];
    }

    /**
     * Sets uid
     * @param string $uid uid
     * @return $this
     */
    public function setUid($uid)
    {
        $this->container['uid'] = $uid;

        return $this;
    }

    /**
     * Gets analysis_ref_uid
     * @return string
     */
    public function getAnalysisRefUid()
    {
        return $this->container['analysis_ref_uid'];
    }

    /**
     * Sets analysis_ref_uid
     * @param string $analysis_ref_uid analysisRefUid
     * @return $this
     */
    public function setAnalysisRefUid($analysis_ref_uid)
    {
        $this->container['analysis_ref_uid'] = $analysis_ref_uid;

        return $this;
    }

    /**
     * Gets check_report_summary
     * @return \idcheckio\model\CheckSummaryOfTheSubmittedDocument
     */
    public function getCheckReportSummary()
    {
        return $this->container['check_report_summary'];
    }

    /**
     * Sets check_report_summary
     * @param \idcheckio\model\CheckSummaryOfTheSubmittedDocument $check_report_summary
     * @return $this
     */
    public function setCheckReportSummary($check_report_summary)
    {
        $this->container['check_report_summary'] = $check_report_summary;

        return $this;
    }

    /**
     * Gets document_classification
     * @return \idcheckio\model\ClassificationOfTheSubmittedDocument
     */
    public function getDocumentClassification()
    {
        return $this->container['document_classification'];
    }

    /**
     * Sets document_classification
     * @param \idcheckio\model\ClassificationOfTheSubmittedDocument $document_classification
     * @return $this
     */
    public function setDocumentClassification($document_classification)
    {
        $this->container['document_classification'] = $document_classification;

        return $this;
    }

    /**
     * Gets document_detail
     * @return \idcheckio\model\DetailedInformationOfTheSubmittedDocument
     */
    public function getDocumentDetail()
    {
        return $this->container['document_detail'];
    }

    /**
     * Sets document_detail
     * @param \idcheckio\model\DetailedInformationOfTheSubmittedDocument $document_detail
     * @return $this
     */
    public function setDocumentDetail($document_detail)
    {
        $this->container['document_detail'] = $document_detail;

        return $this;
    }

    /**
     * Gets holder_detail
     * @return \idcheckio\model\DetailedInformationOfTheHolderOfTheSubmittedDocument
     */
    public function getHolderDetail()
    {
        return $this->container['holder_detail'];
    }

    /**
     * Sets holder_detail
     * @param \idcheckio\model\DetailedInformationOfTheHolderOfTheSubmittedDocument $holder_detail
     * @return $this
     */
    public function setHolderDetail($holder_detail)
    {
        $this->container['holder_detail'] = $holder_detail;

        return $this;
    }

    /**
     * Gets mrz
     * @return \idcheckio\model\Mrz
     */
    public function getMrz()
    {
        return $this->container['mrz'];
    }

    /**
     * Sets mrz
     * @param \idcheckio\model\Mrz $mrz
     * @return $this
     */
    public function setMrz($mrz)
    {
        $this->container['mrz'] = $mrz;

        return $this;
    }

    /**
     * Gets controls
     * @return \idcheckio\model\ControlGroup[]
     */
    public function getControls()
    {
        return $this->container['controls'];
    }

    /**
     * Sets controls
     * @param \idcheckio\model\ControlGroup[] $controls Performed controls on the submitted document
     * @return $this
     */
    public function setControls($controls)
    {
        $this->container['controls'] = $controls;

        return $this;
    }

    /**
     * Gets image
     * @return \idcheckio\model\ExtractedImage[]
     */
    public function getImage()
    {
        return $this->container['image'];
    }

    /**
     * Sets image
     * @param \idcheckio\model\ExtractedImage[] $image Cropped image of the submitted document according request
     * @return $this
     */
    public function setImage($image)
    {
        $this->container['image'] = $image;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\idcheckio\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\idcheckio\ObjectSerializer::sanitizeForSerialization($this));
    }
}


