<?php
/**
 * DetailedInformationOfTheHolderOfTheSubmittedDocumentTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  com.ariadnext.idcheckio.invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IdCheck.IO API
 *
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace com.ariadnext.idcheckio.invoker;

/**
 * DetailedInformationOfTheHolderOfTheSubmittedDocumentTest Class Doc Comment
 *
 * @category    Class */
// * @description DetailedInformationOfTheHolderOfTheSubmittedDocument
/**
 * @package     com.ariadnext.idcheckio.invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class DetailedInformationOfTheHolderOfTheSubmittedDocumentTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "DetailedInformationOfTheHolderOfTheSubmittedDocument"
     */
    public function testDetailedInformationOfTheHolderOfTheSubmittedDocument()
    {

    }

    /**
     * Test attribute "last_name"
     */
    public function testPropertyLastName()
    {

    }

    /**
     * Test attribute "first_name"
     */
    public function testPropertyFirstName()
    {

    }

    /**
     * Test attribute "usage_name"
     */
    public function testPropertyUsageName()
    {

    }

    /**
     * Test attribute "nationality"
     */
    public function testPropertyNationality()
    {

    }

    /**
     * Test attribute "gender"
     */
    public function testPropertyGender()
    {

    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {

    }

    /**
     * Test attribute "birth_date"
     */
    public function testPropertyBirthDate()
    {

    }

    /**
     * Test attribute "birth_place"
     */
    public function testPropertyBirthPlace()
    {

    }

    /**
     * Test attribute "birth_dpt"
     */
    public function testPropertyBirthDpt()
    {

    }

    /**
     * Test attribute "extra_infos"
     */
    public function testPropertyExtraInfos()
    {

    }

}
