<?php
/**
 * Image
 *
 * PHP version 5
 *
 * @category Class
 * @package  invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IdCheck.IO API
 *
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace model;

use \ArrayAccess;

/**
 * Image Class Doc Comment
 *
 * @category    Class */
/** 
 * @package     invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class Image implements ArrayAccess
{
    /**
      * The original name of the model.
      * @var string
      */
    protected static $swaggerModelName = 'Image';

    /**
      * Array of property to type mappings. Used for (de)serialization
      * @var string[]
      */
    protected static $swaggerTypes = array(
        'doc' => 'string',
        'face' => 'string',
        'raw_type' => 'string',
        'light' => 'string'
    );

    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of attributes where the key is the local name, and the value is the original name
     * @var string[]
     */
    protected static $attributeMap = array(
        'doc' => 'doc',
        'face' => 'face',
        'raw_type' => 'rawType',
        'light' => 'light'
    );

    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     * @var string[]
     */
    protected static $setters = array(
        'doc' => 'setDoc',
        'face' => 'setFace',
        'raw_type' => 'setRawType',
        'light' => 'setLight'
    );

    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     * @var string[]
     */
    protected static $getters = array(
        'doc' => 'getDoc',
        'face' => 'getFace',
        'raw_type' => 'getRawType',
        'light' => 'getLight'
    );

    public static function getters()
    {
        return self::$getters;
    }

    const DOC_CNI_BE_SPECIMEN = 'CNI_BE_SPECIMEN';
    const DOC_CNI_BE_SPECIMEN_MRZ = 'CNI_BE_SPECIMEN_MRZ';
    const DOC_PASSEPORT_FR_SPECIMEN_NATACHA = 'PASSEPORT_FR_SPECIMEN_NATACHA';
    const DOC_PASSEPORT_FR_SPECIMEN_NATACHA_MRZ = 'PASSEPORT_FR_SPECIMEN_NATACHA_MRZ';
    const DOC_CNI_FR_SPECIMEN_BERTHIER = 'CNI_FR_SPECIMEN_BERTHIER';
    const DOC_CNI_FR_SPECIMEN_BERTHIER_MRZ = 'CNI_FR_SPECIMEN_BERTHIER_MRZ';
    const DOC_PASSEPORT_FR_SPECIMEN_GRAUX_MRZ = 'PASSEPORT_FR_SPECIMEN_GRAUX_MRZ';
    const DOC_PASSEPORT_FR_SPECIMEN_GRAUX = 'PASSEPORT_FR_SPECIMEN_GRAUX';
    const DOC_CNI_BIH_SPECIMEN = 'CNI_BIH_SPECIMEN';
    const DOC_CNI_BIH_SPECIMEN_MRZ = 'CNI_BIH_SPECIMEN_MRZ';
    const DOC_PASSEPORT_USA_FALSIFIE_TRAVELER = 'PASSEPORT_USA_FALSIFIE_TRAVELER';
    const DOC_PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ = 'PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ';
    const DOC_RP_FR_SPECIMEN_MARTIN = 'RP_FR_SPECIMEN_MARTIN';
    const DOC_RP_FR_SPECIMEN_MARTIN_MRZ = 'RP_FR_SPECIMEN_MARTIN_MRZ';
    const DOC_CNI_GBR_SPECIMEN_FREEMAN = 'CNI_GBR_SPECIMEN_FREEMAN';
    const DOC_CNI_GBR_SPECIMEN_FREEMAN_MRZ = 'CNI_GBR_SPECIMEN_FREEMAN_MRZ';
    const DOC_PASSEPORT_CHN_SPECIMEN_ZHENGJIAN = 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN';
    const DOC_PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ = 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ';
    const DOC_PASSEPORT_ITA_SPECIMEN_ROSSI = 'PASSEPORT_ITA_SPECIMEN_ROSSI';
    const DOC_PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ = 'PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ';
    const DOC_RP_GBR_SPECIMEN_IVANOVA = 'RP_GBR_SPECIMEN_IVANOVA';
    const DOC_RP_GBR_SPECIMEN_IVANOVA_MRZ = 'RP_GBR_SPECIMEN_IVANOVA_MRZ';
    const DOC_DL_FR_SPECIMEN_MARTIN = 'DL_FR_SPECIMEN_MARTIN';
    const DOC_DL_FR_SPECIMEN_MARTIN_MRZ = 'DL_FR_SPECIMEN_MARTIN_MRZ';
    const DOC_ELECTRICITE_FR_BERTHIER = 'ELECTRICITE_FR_BERTHIER';
    const DOC_IMPOSITION_FR_BERTHIER = 'IMPOSITION_FR_BERTHIER';
    const DOC_RIB_FR_BERTHIER = 'RIB_FR_BERTHIER';
    const DOC_TELEPHONE_2_DDOC_BERTHIER = 'TELEPHONE_2DDOC_BERTHIER';
    const DOC_CARTE_GRISE_DUPONT = 'CARTE_GRISE_DUPONT';
    const DOC_SALAIRE_FR_BERTHIER = 'SALAIRE_FR_BERTHIER';
    const FACE_RECTO = 'RECTO';
    const FACE_VERSO = 'VERSO';
    const RAW_TYPE_BASE64 = 'BASE64';
    const RAW_TYPE_JPG = 'JPG';
    const LIGHT_DL = 'DL';
    const LIGHT_IR = 'IR';
    const LIGHT_UV = 'UV';
    

    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getDocAllowableValues()
    {
        return [
            self::DOC_CNI_BE_SPECIMEN,
            self::DOC_CNI_BE_SPECIMEN_MRZ,
            self::DOC_PASSEPORT_FR_SPECIMEN_NATACHA,
            self::DOC_PASSEPORT_FR_SPECIMEN_NATACHA_MRZ,
            self::DOC_CNI_FR_SPECIMEN_BERTHIER,
            self::DOC_CNI_FR_SPECIMEN_BERTHIER_MRZ,
            self::DOC_PASSEPORT_FR_SPECIMEN_GRAUX_MRZ,
            self::DOC_PASSEPORT_FR_SPECIMEN_GRAUX,
            self::DOC_CNI_BIH_SPECIMEN,
            self::DOC_CNI_BIH_SPECIMEN_MRZ,
            self::DOC_PASSEPORT_USA_FALSIFIE_TRAVELER,
            self::DOC_PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ,
            self::DOC_RP_FR_SPECIMEN_MARTIN,
            self::DOC_RP_FR_SPECIMEN_MARTIN_MRZ,
            self::DOC_CNI_GBR_SPECIMEN_FREEMAN,
            self::DOC_CNI_GBR_SPECIMEN_FREEMAN_MRZ,
            self::DOC_PASSEPORT_CHN_SPECIMEN_ZHENGJIAN,
            self::DOC_PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ,
            self::DOC_PASSEPORT_ITA_SPECIMEN_ROSSI,
            self::DOC_PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ,
            self::DOC_RP_GBR_SPECIMEN_IVANOVA,
            self::DOC_RP_GBR_SPECIMEN_IVANOVA_MRZ,
            self::DOC_DL_FR_SPECIMEN_MARTIN,
            self::DOC_DL_FR_SPECIMEN_MARTIN_MRZ,
            self::DOC_ELECTRICITE_FR_BERTHIER,
            self::DOC_IMPOSITION_FR_BERTHIER,
            self::DOC_RIB_FR_BERTHIER,
            self::DOC_TELEPHONE_2_DDOC_BERTHIER,
            self::DOC_CARTE_GRISE_DUPONT,
            self::DOC_SALAIRE_FR_BERTHIER,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getFaceAllowableValues()
    {
        return [
            self::FACE_RECTO,
            self::FACE_VERSO,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getRawTypeAllowableValues()
    {
        return [
            self::RAW_TYPE_BASE64,
            self::RAW_TYPE_JPG,
        ];
    }
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public function getLightAllowableValues()
    {
        return [
            self::LIGHT_DL,
            self::LIGHT_IR,
            self::LIGHT_UV,
        ];
    }
    

    /**
     * Associative array for storing property values
     * @var mixed[]
     */
    protected $container = array();

    /**
     * Constructor
     * @param mixed[] $data Associated array of property value initalizing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['doc'] = isset($data['doc']) ? $data['doc'] : null;
        $this->container['face'] = isset($data['face']) ? $data['face'] : null;
        $this->container['raw_type'] = isset($data['raw_type']) ? $data['raw_type'] : null;
        $this->container['light'] = isset($data['light']) ? $data['light'] : null;
    }

    /**
     * show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalid_properties = array();
        $allowed_values = array("CNI_BE_SPECIMEN", "CNI_BE_SPECIMEN_MRZ", "PASSEPORT_FR_SPECIMEN_NATACHA", "PASSEPORT_FR_SPECIMEN_NATACHA_MRZ", "CNI_FR_SPECIMEN_BERTHIER", "CNI_FR_SPECIMEN_BERTHIER_MRZ", "PASSEPORT_FR_SPECIMEN_GRAUX_MRZ", "PASSEPORT_FR_SPECIMEN_GRAUX", "CNI_BIH_SPECIMEN", "CNI_BIH_SPECIMEN_MRZ", "PASSEPORT_USA_FALSIFIE_TRAVELER", "PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ", "RP_FR_SPECIMEN_MARTIN", "RP_FR_SPECIMEN_MARTIN_MRZ", "CNI_GBR_SPECIMEN_FREEMAN", "CNI_GBR_SPECIMEN_FREEMAN_MRZ", "PASSEPORT_CHN_SPECIMEN_ZHENGJIAN", "PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ", "PASSEPORT_ITA_SPECIMEN_ROSSI", "PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ", "RP_GBR_SPECIMEN_IVANOVA", "RP_GBR_SPECIMEN_IVANOVA_MRZ", "DL_FR_SPECIMEN_MARTIN", "DL_FR_SPECIMEN_MARTIN_MRZ", "ELECTRICITE_FR_BERTHIER", "IMPOSITION_FR_BERTHIER", "RIB_FR_BERTHIER", "TELEPHONE_2DDOC_BERTHIER", "CARTE_GRISE_DUPONT", "SALAIRE_FR_BERTHIER");
        if (!in_array($this->container['doc'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'doc', must be one of #{allowed_values}.";
        }

        $allowed_values = array("RECTO", "VERSO");
        if (!in_array($this->container['face'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'face', must be one of #{allowed_values}.";
        }

        $allowed_values = array("BASE64", "JPG");
        if (!in_array($this->container['raw_type'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'raw_type', must be one of #{allowed_values}.";
        }

        $allowed_values = array("DL", "IR", "UV");
        if (!in_array($this->container['light'], $allowed_values)) {
            $invalid_properties[] = "invalid value for 'light', must be one of #{allowed_values}.";
        }

        return $invalid_properties;
    }

    /**
     * validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properteis are valid
     */
    public function valid()
    {
        $allowed_values = array("CNI_BE_SPECIMEN", "CNI_BE_SPECIMEN_MRZ", "PASSEPORT_FR_SPECIMEN_NATACHA", "PASSEPORT_FR_SPECIMEN_NATACHA_MRZ", "CNI_FR_SPECIMEN_BERTHIER", "CNI_FR_SPECIMEN_BERTHIER_MRZ", "PASSEPORT_FR_SPECIMEN_GRAUX_MRZ", "PASSEPORT_FR_SPECIMEN_GRAUX", "CNI_BIH_SPECIMEN", "CNI_BIH_SPECIMEN_MRZ", "PASSEPORT_USA_FALSIFIE_TRAVELER", "PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ", "RP_FR_SPECIMEN_MARTIN", "RP_FR_SPECIMEN_MARTIN_MRZ", "CNI_GBR_SPECIMEN_FREEMAN", "CNI_GBR_SPECIMEN_FREEMAN_MRZ", "PASSEPORT_CHN_SPECIMEN_ZHENGJIAN", "PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ", "PASSEPORT_ITA_SPECIMEN_ROSSI", "PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ", "RP_GBR_SPECIMEN_IVANOVA", "RP_GBR_SPECIMEN_IVANOVA_MRZ", "DL_FR_SPECIMEN_MARTIN", "DL_FR_SPECIMEN_MARTIN_MRZ", "ELECTRICITE_FR_BERTHIER", "IMPOSITION_FR_BERTHIER", "RIB_FR_BERTHIER", "TELEPHONE_2DDOC_BERTHIER", "CARTE_GRISE_DUPONT", "SALAIRE_FR_BERTHIER");
        if (!in_array($this->container['doc'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("RECTO", "VERSO");
        if (!in_array($this->container['face'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("BASE64", "JPG");
        if (!in_array($this->container['raw_type'], $allowed_values)) {
            return false;
        }
        $allowed_values = array("DL", "IR", "UV");
        if (!in_array($this->container['light'], $allowed_values)) {
            return false;
        }
        return true;
    }


    /**
     * Gets doc
     * @return string
     */
    public function getDoc()
    {
        return $this->container['doc'];
    }

    /**
     * Sets doc
     * @param string $doc
     * @return $this
     */
    public function setDoc($doc)
    {
        $allowed_values = array('CNI_BE_SPECIMEN', 'CNI_BE_SPECIMEN_MRZ', 'PASSEPORT_FR_SPECIMEN_NATACHA', 'PASSEPORT_FR_SPECIMEN_NATACHA_MRZ', 'CNI_FR_SPECIMEN_BERTHIER', 'CNI_FR_SPECIMEN_BERTHIER_MRZ', 'PASSEPORT_FR_SPECIMEN_GRAUX_MRZ', 'PASSEPORT_FR_SPECIMEN_GRAUX', 'CNI_BIH_SPECIMEN', 'CNI_BIH_SPECIMEN_MRZ', 'PASSEPORT_USA_FALSIFIE_TRAVELER', 'PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ', 'RP_FR_SPECIMEN_MARTIN', 'RP_FR_SPECIMEN_MARTIN_MRZ', 'CNI_GBR_SPECIMEN_FREEMAN', 'CNI_GBR_SPECIMEN_FREEMAN_MRZ', 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN', 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ', 'PASSEPORT_ITA_SPECIMEN_ROSSI', 'PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ', 'RP_GBR_SPECIMEN_IVANOVA', 'RP_GBR_SPECIMEN_IVANOVA_MRZ', 'DL_FR_SPECIMEN_MARTIN', 'DL_FR_SPECIMEN_MARTIN_MRZ', 'ELECTRICITE_FR_BERTHIER', 'IMPOSITION_FR_BERTHIER', 'RIB_FR_BERTHIER', 'TELEPHONE_2DDOC_BERTHIER', 'CARTE_GRISE_DUPONT', 'SALAIRE_FR_BERTHIER');
        if (!in_array($doc, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'doc', must be one of 'CNI_BE_SPECIMEN', 'CNI_BE_SPECIMEN_MRZ', 'PASSEPORT_FR_SPECIMEN_NATACHA', 'PASSEPORT_FR_SPECIMEN_NATACHA_MRZ', 'CNI_FR_SPECIMEN_BERTHIER', 'CNI_FR_SPECIMEN_BERTHIER_MRZ', 'PASSEPORT_FR_SPECIMEN_GRAUX_MRZ', 'PASSEPORT_FR_SPECIMEN_GRAUX', 'CNI_BIH_SPECIMEN', 'CNI_BIH_SPECIMEN_MRZ', 'PASSEPORT_USA_FALSIFIE_TRAVELER', 'PASSEPORT_USA_FALSIFIE_TRAVELER_MRZ', 'RP_FR_SPECIMEN_MARTIN', 'RP_FR_SPECIMEN_MARTIN_MRZ', 'CNI_GBR_SPECIMEN_FREEMAN', 'CNI_GBR_SPECIMEN_FREEMAN_MRZ', 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN', 'PASSEPORT_CHN_SPECIMEN_ZHENGJIAN_MRZ', 'PASSEPORT_ITA_SPECIMEN_ROSSI', 'PASSEPORT_ITA_SPECIMEN_ROSSI_MRZ', 'RP_GBR_SPECIMEN_IVANOVA', 'RP_GBR_SPECIMEN_IVANOVA_MRZ', 'DL_FR_SPECIMEN_MARTIN', 'DL_FR_SPECIMEN_MARTIN_MRZ', 'ELECTRICITE_FR_BERTHIER', 'IMPOSITION_FR_BERTHIER', 'RIB_FR_BERTHIER', 'TELEPHONE_2DDOC_BERTHIER', 'CARTE_GRISE_DUPONT', 'SALAIRE_FR_BERTHIER'");
        }
        $this->container['doc'] = $doc;

        return $this;
    }

    /**
     * Gets face
     * @return string
     */
    public function getFace()
    {
        return $this->container['face'];
    }

    /**
     * Sets face
     * @param string $face
     * @return $this
     */
    public function setFace($face)
    {
        $allowed_values = array('RECTO', 'VERSO');
        if (!in_array($face, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'face', must be one of 'RECTO', 'VERSO'");
        }
        $this->container['face'] = $face;

        return $this;
    }

    /**
     * Gets raw_type
     * @return string
     */
    public function getRawType()
    {
        return $this->container['raw_type'];
    }

    /**
     * Sets raw_type
     * @param string $raw_type
     * @return $this
     */
    public function setRawType($raw_type)
    {
        $allowed_values = array('BASE64', 'JPG');
        if (!in_array($raw_type, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'raw_type', must be one of 'BASE64', 'JPG'");
        }
        $this->container['raw_type'] = $raw_type;

        return $this;
    }

    /**
     * Gets light
     * @return string
     */
    public function getLight()
    {
        return $this->container['light'];
    }

    /**
     * Sets light
     * @param string $light
     * @return $this
     */
    public function setLight($light)
    {
        $allowed_values = array('DL', 'IR', 'UV');
        if (!in_array($light, $allowed_values)) {
            throw new \InvalidArgumentException("Invalid value for 'light', must be one of 'DL', 'IR', 'UV'");
        }
        $this->container['light'] = $light;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     * @param  integer $offset Offset
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     * @param  integer $offset Offset
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     * @param  integer $offset Offset
     * @param  mixed   $value  Value to be set
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     * @param  integer $offset Offset
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(\invoker\ObjectSerializer::sanitizeForSerialization($this), JSON_PRETTY_PRINT);
        }

        return json_encode(\invoker\ObjectSerializer::sanitizeForSerialization($this));
    }
}


