<?php
/**
 * ImageRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  invoker
 * @author   http://github.com/swagger-api/swagger-codegen
 * @license  http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * IdCheck.IO API
 *
 * Check identity documents
 *
 * OpenAPI spec version: 0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace invoker;

/**
 * ImageRequestTest Class Doc Comment
 *
 * @category    Class */
// * @description ImageRequest
/**
 * @package     invoker
 * @author      http://github.com/swagger-api/swagger-codegen
 * @license     http://www.apache.org/licenses/LICENSE-2.0 Apache Licene v2
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ImageRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {

    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {

    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {

    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {

    }

    /**
     * Test "ImageRequest"
     */
    public function testImageRequest()
    {

    }

    /**
     * Test attribute "api_version"
     */
    public function testPropertyApiVersion()
    {

    }

    /**
     * Test attribute "front_image"
     */
    public function testPropertyFrontImage()
    {

    }

    /**
     * Test attribute "front_image_ir"
     */
    public function testPropertyFrontImageIr()
    {

    }

    /**
     * Test attribute "front_image_uv"
     */
    public function testPropertyFrontImageUv()
    {

    }

    /**
     * Test attribute "back_image"
     */
    public function testPropertyBackImage()
    {

    }

    /**
     * Test attribute "back_image_ir"
     */
    public function testPropertyBackImageIr()
    {

    }

    /**
     * Test attribute "back_image_uv"
     */
    public function testPropertyBackImageUv()
    {

    }

    /**
     * Test attribute "recto_image_cropped"
     */
    public function testPropertyRectoImageCropped()
    {

    }

    /**
     * Test attribute "face_image_cropped"
     */
    public function testPropertyFaceImageCropped()
    {

    }

    /**
     * Test attribute "signature_image_cropped"
     */
    public function testPropertySignatureImageCropped()
    {

    }

}
